<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head><title>PHP3</title></head><body><?php
      $tag = 'phptag';
      $class = 'phpclass';
?><<?=$tag?> class="<?=$class?>">php generated by haml</<?=$tag?>></body></html>